export default[
    'India',
    'America',
    'England',
    'South-Africa',
    'Thailand',
    'Baden',
    'Bahamas',
    'Nauru',
    'Nepal',
    'Netherlands',
    'Bahrain',
    'Bangladesh',
    'Russia',
    'Japan',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'China',
    'Fiji',
    'Finland',
    'France',
    'Australia',
    'Barbados',
    'Bavaria',
    'Dubai',
    'Spain',
   'El Salvador',
   'Equatorial Guinea',
   'Eritrea',
   'Estonia',
   'Pakistan',
   'Palau',
   'Panama',
   'Papal States',
   'Papua New Guinea',
   'Paraguay',
   'Peru',
   'Philippines',
   'Eswatini',
   'Ethiopia',
    'Sri Lanka',
    'Sudan',
    'Belarus',
    'Belgium',
    'Egypt',
    'Zimbabwe',
    'West-Indies',
    'Singapore',
    'Equatorial',
    'EswaEthi'
    
]